### ISSUE TITLE
Update metrics config 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#504]
trying to use the prometheus config file from [here](https://besu.hyperledger.org/en/stable/HowTo/Monitor/Metrics/) - and getting "field job_name not found in type config.plain".

Looks like the config should be: 
```
scrape_configs:
  - job_name: 'besu-dev'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['Localhost:9545']
```
